//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int issueID { get; set; }
        public Nullable<int> room { get; set; }
        public int issueType { get; set; }
        public string issueDescription { get; set; }
        public string note { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> timeIssued { get; set; }
        public Nullable<System.DateTime> timeCompleted { get; set; }
    
        public virtual Room Room1 { get; set; }
    }
}
