//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int bookingID { get; set; }
        public int customerID { get; set; }
        public int roomtype { get; set; }
        public System.DateTime checkinDate { get; set; }
        public System.DateTime checkoutDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
